### ISSUE TITLE
Remove Annotation class?

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/zipkin-php#21]
[Annotation](https://github.com/jcchavezs/zipkin-php/blob/master/src/Zipkin/Annotation.php) was intended to be a value object for holding the guards clause for creating an annotation but actually that can be moved to a `namespace function` and the content can be stored as a `array`.

- In performance terms, according to https://3v4l.org/DQ5jG/perf#output and https://3v4l.org/30jdF/perf#tabs a slightly increase of memory when using arrays but nothing significant whereas the times are way better in arrays than with objects (in both PHP7 and PHP 5.6). There is [post](https://gist.github.com/nikic/5015323) from @nikic explaining why objects use less memory than arrays but an span might not have that many annotations.
- From idiomatic perspective, annotations are opaque meaning that we won't ask any question nor use public methods to it so it makes sense to store as an array rather than as an object.

Ping @beberlei @adriancole @felixfbecker

**Comment by adriancole** [comment]
some struct that is a pair of timestamp/value makes sense. I'll leave it to you for what's idiomatic

**Comment by jcchavezs** [comment]
Ping @basvanbeek

**Comment by jcchavezs** [comment]
Ping @basvanbeek

**Comment by basvanbeek** [comment]
I think a PHP object is more explicit in intention and usage compared to a PHP array. Also think about type completion in a PHP IDE.

**Comment by beberlei** [comment]
Since this is purely internal, I would go with arrays and move the guard clauses in `Span->annotate` (or how they are named) methods. The structure would then be a list of ts,value pairs such as `array( array('ts' => 1234, 'value' => '...'), array('ts' => 1235, 'value' => '...') );`
