### ISSUE TITLE
Replace guzzle with curl in the http reporter 

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/zipkin-php#27]
Since the http reporting is a very simple & straightforward task there is not need to include the full the guzzle dependency for such an action. A curl implementation could be easily shipped for HTTP reporter. There are some pros and cons:

**Pros:**
- Removes the Guzzle dependency

**Cons:**
- Need to wrap the curl function calls with an interface that could be mocked. We already mock the client for unit test.

**One very important concern is whether we keep the intention to unit test it or to do some integration tests.**

Ping @basvanbeek @beberlei @felixfbecker @adriancole

**Comment by beberlei** [comment]
Yes please, that sounds like a good change.

**Comment by felixfbecker** [comment]
Does curl work on Windows?

**Comment by jcchavezs** [comment]
@felixfbecker as far as I know the PHP extension works.
