### ISSUE TITLE
Could you make a tag for composer require ?

### ISSUE THREAD

**Issue by cc5092** [jcchavezs/zipkin-php#31]
As you say: "This is a production ready PHP library for Zipkin."

But this does have no version tag for composer to require. And I must to do like this
`composer require jcchavezs/zipkin:dev-master`

**Comment by jcchavezs** [comment]
Great point, I just created a release: https://github.com/jcchavezs/zipkin-php/releases/tag/1.0.0-beta1

Mind to have a chat about how you are using zipkin in PHP? https://gitter.im/jcchavezs

**Comment by adriancole** [comment]
Nice! Hope you two had a good chat ;)

**Comment by cc5092** [comment]
greate job, and I found some bugs and will commit a pr. please review it later~
