### ISSUE TITLE
Drop options param for HttpLogging

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/zipkin-php#38]
I could not think in additional options we could pass to the [HttpLogging](https://github.com/jcchavezs/zipkin-php/blob/master/src/Zipkin/Reporters/HttpLogging.php) in the constructor. Its functioning is pretty simple and the only parameter I could think of is the endpoint url.

Comments @basvanbeek @adriancole @beberlei @felixfbecker

**Comment by basvanbeek** [comment]
How do you want to deal with http client options (adding custom headers, setting timeouts, etc.?)

**Comment by jcchavezs** [comment]
Request things right now go in the [injected client](http://docs.guzzlephp.org/en/stable/quickstart.html#creating-a-client), however there is [this issue](https://github.com/jcchavezs/zipkin-php/issues/27) where I plan to drop the client and use curl so maybe it makes sense to keep the options. Maybe we need to keep this on hold until we decide on https://github.com/jcchavezs/zipkin-php/issues/27.
