### ISSUE TITLE
Endpoint::createFromGlobals() spills warnings on PHP-CLI

### ISSUE THREAD

**Issue by beberlei** [jcchavezs/zipkin-php#6]
Accessing `$_SERVER['SERVER_SOFTWARE']` depends on the SAPI, on php cli it is empty.

The code should use `php_sapi_name()` if the server software key is not set.

Additionally, on nginx+fpm the `SERVER_SOFTWARE` says nginx, but that is wrong as well. It should maybe always put the SAPI in there, because the webserver is actually another layer.

**Comment by jcchavezs** [comment]
Great feedback, @beberlei. I will fix it.

**Comment by jcchavezs** [comment]
Closed by https://github.com/jcchavezs/zipkin-php/pull/12

**Comment by jcchavezs** [comment]
Closed by https://github.com/jcchavezs/zipkin-php/pull/12
