### ISSUE TITLE
Zipkin\Reporters\Http is not compatible with PHP 5.6

### ISSUE THREAD

**Issue by eligijusvitkauskas-home24** [jcchavezs/zipkin-php#62]
PHP 5.6 does not support arrays as constants therefore this leads to a fatal error on PHP 5.6

**Comment by jcchavezs** [comment]
Hi @eligijusvitkauskas-home24 

Thanks for contributing!

However I am not sure about this. According to PHP documentation PHP constant array [has been introduced](http://php.net/manual/en/migration56.new-features.php) in PHP 5.6, plus this class run unit tests against to PHP 5.6 version so maybe you refer to 5.5.9? Can you please confirm that?

**Comment by eligijusvitkauskas-home24** [comment]
You are correct sir, sorry for a false issue.

**Comment by jcchavezs** [comment]
No worries @eligijusvitkauskas-home24 ! Thanks for being here. If you really need zipkin in PHP 5.5 feel free to open a PR!
