### ISSUE TITLE
Consider adding Kafka transport for a future release

### ISSUE THREAD

**Issue by GreedyPirate** [jcchavezs/zipkin-php#74]
hi，I am ready for use zipkin-php, and hope to add Kafka transport for a future release, for two send type http and kafka mq, configurable will be nice

My env list at below
php version : php 7.1.14
kafka-client : nmred/kafka-php
kafka-version : 0.9
zipkin-server versoin : 2.8.3

**Comment by jcchavezs** [comment]
I just started this: https://github.com/jcchavezs/zipkin-php-reporter-kafka

**Comment by GreedyPirate** [comment]
I will follow up 👍
