### ISSUE TITLE
spl_object_hash() causing recorders to produce incorrect span data

### ISSUE THREAD

**Issue by Aramack** [jcchavezs/zipkin-php#76]
I have been seeing strange behavior where some spans are not being reported and others are getting assigned tags from the wrong places.

This can be demonstrated with:
```
<?php
$reporter = new Zipkin\Reporters\Http(null, ['endpoint_url' => 'http://10.228.128.48:9411/api/v2/spans']);
$traceContext = \Zipkin\Propagation\TraceContext::createAsRoot(\Zipkin\Propagation\DefaultSamplingFlags::create(true));
$currentTraceContext = \Zipkin\Propagation\CurrentTraceContext::create($traceContext);
$tracer = \Zipkin\TracingBuilder::create()
        ->havingSampler(\Zipkin\Samplers\BinarySampler::createAsAlwaysSample())
        ->havingCurrentTraceContext($currentTraceContext)
        ->havingReporter($reporter)
        ->build()->getTracer();
$rootSpan = $tracer->newChild($tracer->getCurrentSpan()->getContext());
$rootSpan->setName('outerspan');
$rootSpan->start();

for ($i = 0 ; $i < 5; $i++) {
  $childSpan = $tracer->newChild($rootSpan->getContext());
  echo('childSpan spanId: ' . $childSpan->getContext()->getSpanId() . ' spl_object_hash(): ' . spl_object_hash($childSpan->getContext()) . PHP_EOL);
  $childSpan->setName('innerspan'.$i);
  $childSpan->start();
  sleep(1);
  $childSpan->finish();

}

$rootSpan->finish();
$tracer->flush();
?>
```

Screen shot attached of the trace visulaized in zipkins.
![image](https://user-images.githubusercontent.com/5994631/41684175-bbee718a-74aa-11e8-9af1-0415eb9bce80.png)

```
php -f test.php
childSpan spanId: 2d8ca211f7ca3e00 spl_object_hash(): 00000000391e629e000000003f30782e
childSpan spanId: 3c3c583894079703 spl_object_hash(): 00000000391e6291000000003f30782e
childSpan spanId: 5eda3ed654de34e5 spl_object_hash(): 00000000391e629e000000003f30782e
childSpan spanId: a02da70f7a84e59c spl_object_hash(): 00000000391e6292000000003f30782e
childSpan spanId: 6101793fb8afd412 spl_object_hash(): 00000000391e629e000000003f30782e
```

Notice that on lines 1, 3 and 5 the result of spl_object_hash are the same despite the fact that they are different spans. This is caused by PHP running garbage collection and destroy the spans that were created in the for loop. Per http://php.net/manual/en/function.spl-object-hash.php, "once the object is destroyed, its hash may be reused for other objects." This causes the span recorders to overrite previous data because it seems them as the same object.

My suggestion is to change \Zipkin\Recording\SpanMap->getHash() https://github.com/jcchavezs/zipkin-php/blob/master/src/Zipkin/Recording/SpanMap.php#L88 to a hash of some combination of the spanId, parentSpanId and TraceId. This should produce an equally consistent hash for a span context, without relying on spl_obhect_hash().

```hash('sha256', $context->getSpanId() . $context->getParentId() . $context->getTraceId());```

**Comment by jcchavezs** [comment]
Hi @Aramack,

Thanks for this awesomely explained issue.

Regarding this hashing, when wrote the library the first approach was to use something similar to what you mention:

`md5($context->getSpanId() . ($context->getParentId() ?: "-") . $context->getTraceId())`

Because `$context->getParentId()` con return `null`. 

My only question is that wether it should be that order or the other way around (traceID - parentID - spanID) but maybe it does not matter.

Either way, given that you have a been a very nice issue reporter, would you mind to create a PR fixing this and a test with it?

Again, thanks for participating!

**Comment by Aramack** [comment]
I've been running some tests with a few different hashing algorithms. 
![image](https://user-images.githubusercontent.com/5994631/41796980-59c4a64a-7636-11e8-8ce8-3282b9c996d5.png)
There's a small performance hit of about 3 microseconds, but I can confirm this fixes the problem I've been seeing:
![image](https://user-images.githubusercontent.com/5994631/41797079-b2c7e270-7636-11e8-94d7-e5ab60cbf0ff.png)

**Comment by jcchavezs** [comment]
Closed by https://github.com/jcchavezs/zipkin-php/pull/78. Thanks @Aramack!
